from logic_utils import check_guess, update_score

def test_winning_guess():
    # FIX: If the secret is 50 and guess is 50, it should be a win with correct message
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = check_guess(50, 50)
    assert result == ("Win", "🎉 Correct!")

def test_guess_too_high():
    # FIX: If the secret is 50 and guess is 60, it should be "Too High" and "Go LOWER"
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = check_guess(60, 50)
    assert result == ("Too High", "📉 Go LOWER!")

def test_guess_too_low():
    # FIX: If the secret is 50 and guess is 40, it should be "Too Low" and "Go HIGHER"
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = check_guess(40, 50)
    assert result == ("Too Low", "📈 Go HIGHER!")

def test_update_score_too_high_subtracts_5():
    # FIX: wrong guesses must subtract 5 points, previously"Too High" guessses on even attempts added 5 points
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = update_score(0, "Too High", 2)
    assert result == -5

def test_update_score_too_low_subtracts_5():
    # FIX: wrong guesses must subtract 5 points
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = update_score(0, "Too Low", 2)
    assert result == -5
