from logic_utils import check_guess, update_score, parse_guess

def test_winning_guess():
    # FIX: If the secret is 50 and guess is 50, it should be a win with correct message
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = check_guess(50, 50)
    assert result == ("Win", "🎉 Correct!")

def test_guess_too_high():
    # FIX: If the secret is 50 and guess is 60, it should be "Too High" and "Go LOWER"
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = check_guess(60, 50)
    assert result == ("Too High", "📉 Go LOWER!")

def test_guess_too_low():
    # FIX: If the secret is 50 and guess is 40, it should be "Too Low" and "Go HIGHER"
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = check_guess(40, 50)
    assert result == ("Too Low", "📈 Go HIGHER!")

def test_update_score_too_high_subtracts_5():
    # FIX: wrong guesses must subtract 5 points, previously"Too High" guessses on even attempts added 5 points
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = update_score(0, "Too High", 2)
    assert result == -5

def test_update_score_too_low_subtracts_5():
    # FIX: wrong guesses must subtract 5 points
    # Tests generated by Claude in VS Code, verified by running pytest and the live game.
    result = update_score(0, "Too Low", 2)
    assert result == -5

def test_parse_guess_non_numeric_string():
    # EDGE CASE: alphabetic input should fail with "That is not a number."
    # parse_guess raises no exception — it returns (False, None, error_msg).
    result = parse_guess("abc")
    assert result == (False, None, "That is not a number.")

def test_parse_guess_negative_number():
    # EDGE CASE: negative numbers pass validation with no range check.
    # parse_guess currently accepts "-5" and returns (True, -5, None).
    # Note: range enforcement (if ever added) would live outside parse_guess.
    result = parse_guess("-5")
    assert result == (True, -5, None)

def test_parse_guess_decimal_truncated():
    # EDGE CASE: decimals are silently truncated to int via int(float(raw)).
    # "3.7" becomes 3, not rounded to 4.
    result = parse_guess("3.7")
    assert result == (True, 3, None)
